### ISSUE TITLE
Grouped partitions

### ISSUE THREAD

**Issue by clementfarabet** [twitter/torch-dataset#10]
It would be nice to have a system of grouped partitions, useful for creating splits on the fly (training/validation):

```lua
trainingPartition = {
   partitions = 10
   partition = {1,2,3,4,5,6,7,8,9}
}
validationPartition = {
   partitions = 10
   partition = {10}
}
```

**Comment by egonina** [comment]
@clementfarabet do you want the files to be round-robined to partitions or is it ok to split them into chunks sequentially?

**Comment by clementfarabet** [comment]
Closing – this overloading of partitions is too confusing.
