### ISSUE TITLE
walk through index.csv file in order?

### ISSUE THREAD

**Issue by willfrey** [twitter/torch-dataset#13]
How can I walk through my index.csv file from the first entry to the last? For example, if I've sorted the index.csv file by sample length — since I have variable length training data — I'd like to walk through from the shortest to the longest.

Setting samplerKind = 'linear' appears to walk through in the same order but not in the order given in the index.csv file.

Is there any way to achieve this behavior?

**Comment by zakattacktwitter** [comment]
Unfortunately there is currently no way to do this, however its been on my
list to fix for some time now.

**Comment by zakattacktwitter** [comment]
See issue #9, I'll try and implement this soon. Thanks!
