### ISSUE TITLE
module 'libdataset' not found

### ISSUE THREAD

**Issue by willfrey** [twitter/torch-dataset#18]
As of the most recent changes, I'm getting this error

> module 'libdataset' not found:No LuaRocks module found for libdataset

The offender seems to be line 8 of Cache.lua. How can I fix this?

Thanks!

**Comment by zakattacktwitter** [comment]
Hmm,

It works for me, and CI is passing (ignore the Lua 5.2 errors).
https://travis-ci.org/twitter/torch-dataset

Can you try rebuilding it? Perhaps luarocks make needs encouragement.

**Comment by willfrey** [comment]
It appears that `luarocks make dataset-scm-1.rockspec` makes it work but `luarocks install dataset` breaks it.

**Comment by joeyhng** [comment]
Same issue for me. ```luarocks make dataset-scm-1.rockspec``` works but ```luarocks install dataset``` doesn't.

**Comment by Halflernation** [comment]
Guys, and how do you make from the rockspec?

"cannot stat 'lua/Index.lua': No such file or directory."

**Comment by zakattacktwitter** [comment]
Hi,

The only command you need to run is:

luarocks make

That should build and install everything.

Thanks,
Zak
