### ISSUE TITLE
A bug may exist when tensors is the input to Dataset

### ISSUE THREAD

**Issue by jundeng86** [twitter/torch-dataset#20]
There may be a small bug when tensors is the input to Dataset. The following code should work if I didn't misunderstand the code. But it didn't work as expected. 
```lua
DS = require 'dataset.Dataset'
dataset = DS({x=torch.randn(100, 9),y=torch.randn(100)})
print(dataset.index)
```
If the code above is corrected as follows, then it works. 
```lua
DS = require 'dataset.Dataset'
dataset = DS({{x=torch.randn(100, 9),y=torch.randn(100)}})
print(dataset.index)
```

Could you please correct the bug? Thanks!

Jun

**Comment by zakattacktwitter** [comment]
Thanks for reporting this, it should be fixed now.
