### ISSUE TITLE
Is there any limitation in the memory when using torch-dataset?

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-dataset#26]
Hi, we saved our data to torch senor format 'train.t7' and loaded it using torch-dataset.

local trainingDataset = Dataset('train.t7', {partition = 1, partitions = 1})

If the size of 'train.t7' is 500GB or more, is there any limitation in the memory when using torch-dataset? Is there any issue when we define 'batchSize' or use 'torch-ipc'?

Thank you.

**Comment by zakattacktwitter** [comment]
This is the same as https://github.com/twitter/torch-ipc/issues/23 so I am answering there, closing this one. Thanks.
