### ISSUE TITLE
How to use SlowFS?

### ISSUE THREAD

**Issue by chienlinhuang1116** [twitter/torch-dataset#30]
Hi,

I would like to use SlowFS but dont know how to use it. Originally, we got data by using following scripts. We indicated a data file and read it to the memory.

```
local dataset = Dataset('/test/hdfs/files/part-r-00000.t7', {partition = 1, partitions = 1})
local getBatch, numBatches = dataset.sampledBatcher({
  samplerKind = 'linear',
  batchSize = 1,
  inputDims = {1},
  processor = function(res, opt, input)
      print(res)
      return true
  end,
})
```

I try to make files can be loaded dynamically as the training/sampler progresses through them. The scripts changed as followings to match our purpose.

```
local dataset = Dataset('viewfs:///test/hdfs/files', {partition = 1, partitions = 1})
local getBatch, numBatches = dataset.sampledBatcher({
  samplerKind = 'part-linear',
  batchSize = 1,
  inputDims = {1},
  processor = function(res, opt, input)
      print(res)
      return true
  end,
})
```

The problem is 'res' should be a 'torch.*Tensor' but it is a 'string' now. Do you have any idea?

Thank you.

**Comment by chienlinhuang1116** [comment]
Hi,

I traced back to Getters.lua and found it will read data using io.open(url, ‘r’) if we use SlowFS or ViewFS. Because of that, we got a binary string instead of a torch float tensor.  
I modified the program and made it return torch.load(url) a torch float tensor. I tested a vector with 680 dimensions and got correct values. But, there are problems to handle a match like 10240x680. How can we use SlowFS and get torch tensor correctly?
```
local function getFile(url, offset, length)
   return torch.load(url)
   --[[local f = io.open(url, 'r')
   if f ~= nil then
      local contents
      if offset ~= nil and length ~= nil then
         if offset >= 0 and length ~= 0 then
            f:seek("set", offset)
            contents = f:read(math.abs(length))
         end
      else
         contents = f:read('*all')
      end
      f:close()
      return contents]]
end
```

Thank you.

**Comment by chienlinhuang1116** [comment]
This related to 

Can we open files by "FloatTensor" instead of "io.popen" when testing "test_StreamedDataset.lua" ? #33

Thank you.

**Comment by zakattacktwitter** [comment]
Hi,

Can you describe what you are trying to do? There's no default
implementation of a SlowFS interface in the github code. Internally at
Twitter we have an implementation that uses Hadoop to fetch files.

It doesn't make sense to hook it up to a tensor. Can you elaborate on what
you are trying to do?

Thanks,
Zak

**Comment by chienlinhuang1116** [comment]
Hi,

I have about one thousand hour speech data. After feature extraction, I have four hundred million vectors and the dimension is about 500 for each floating vector. I would like to use these vectors to train NNs. In examples of mnist.lua and cifar10.lua, we can indicate a small data file and process it. Because now the data is huge, I need to make several thousand chunking files and them can be loaded dynamically as the training/sampler progresses through them.

All I need is the description at https://github.com/twitter/torch-dataset and FloatTensor values.
`We don't always need to have a physical index to create a Dataset, it is also possible to create a Dataset by simply pointing it at a path in SlowFS. In this scenario the Dataset index is built by scanning the SlowFS directory for part files. Part files are loaded dynamically as the training/sampler progresses through them...`

I think SlowFS should be a solution but do not know how to use it. I saw an example at 'test/test_StreamedDataset.lua' but it will return the binary content instead of FloatTensor values.

I found that if modifying 'test/test_StreamedDataset.lua', 'IndexSlowFS.lua' and 'Reader.lua', thousand chunking files can be loaded dynamically and return FloatTensor values. 

IndexSlowFS.lua
```
local function makeFileIndex(fileName, url, opt, idx, SlowFS)
      local Cache = require 'dataset.Cache'
      local cache = Cache(opt)
      local slowFS = SlowFS(cache, opt)
      local fileURL = url .. '/' .. fileName
      local fpath = slowFS.get(fileURL)
      local offsets = {0}
      return {
         url = url,
         fileName = fileName,
         filePath = fpath,
         itemCount = 1,
         offsets = offsets,
         idx = idx,
      }
End
```

Reader.lua
```
if item.offset ~= nil then
    res[i] = torch.load(item.url)
else
    res[i] = resi
end
```

Although it works now, this seems not a formal solution. Do you have any idea? 

Thank you,
Chien-Lin

**Comment by zakattacktwitter** [comment]
Hi,

SlowFS is meant to be used for a slow and remote file system, like Hadoop
or S3. If you have data that’s already on your machines disk then you do
not want to use SlowFS.

I think what you want is more a long the lines of the IndexDirectory setup.
You have a bunch of files on your local disk and just want to construct an
Index/Dataset based on all the files that are present.

The big difference is that IndexDirectory does not currently support files
that are chunks of multiple items. This is something that would be needed
to be added.

A simple fix would be to store all your data in a directory, where each
file represents one tensor that you would like to train on. With that
directory you can simply construct a Dataset and use it.

Hope this helps.

**Comment by chienlinhuang1116** [comment]
Hi,

I have about one thousand hour speech data. After feature extraction, I have four hundred million vectors and the dimension is about 500 for each floating vector. I would like to use these vectors to train NNs. In examples of mnist.lua and cifar10.lua, I can indicate a small data file and process it. Because now the data is huge, I need to make several thousand chunking files and them can be loaded dynamically as the training/sampler progresses through them, and get FloatTensor values.

SlowFS should be a solution but do not know how to use it. There is an example at 'test/test_StreamedDataset.lua' but it returns the binary content instead of FloatTensor values. By modifying 'test/test_StreamedDataset.lua', 'IndexSlowFS.lua' and 'Reader.lua', now thousand chunking files can be loaded dynamically and return FloatTensor values.

Getters.lua

```
local function getters(url, indexType)
   if url and string.sub(url, 1, 4) == 'http' then
      return getHTTP
   else
      return getTensor
   end
end 
```

IndexSlowFS.lua

```
local function makeFileIndex(fileName, url, opt, idx, SlowFS)
      local Cache = require 'dataset.Cache'
      local cache = Cache(opt)
      local slowFS = SlowFS(cache, opt)
      local fileURL = url .. '/' .. fileName
      local fpath = slowFS.get(fileURL)
      local offsets = {0}
      return {
         url = url,
         fileName = fileName,
         filePath = fpath,
         itemCount = 1,
         offsets = offsets,
         idx = idx,
      }
End
```

Reader.lua

```
if item.offset ~= nil then
    res[i] = torch.load(item.url)
else
    res[i] = resi
end
```

Although it works now, this seems not a formal solution. Do you have any idea about these changes? 

I got 4 times faster than a single GPU when using 6 GPUs on testing the small dataset. However, it became much slower when using SlowFS on testing the big dataset. Is it correct?

Thank you,
Chien-Lin

**Comment by chienlinhuang1116** [comment]
Thank you Zak :D 

It works well using IndexDirectory.lua . However, I need to modify Reader.lua in line:77, res[i] = torch.load(item.url) to make it works. The reason why did I modify line:77 is that the return value is the binary content instead of Torch FloatTensor using IndexDirectory.lua.

How can I have the return value like IndexTensor.lua when using IndexDirectory.lua?

Thank you,
Chien-Lin

**Comment by chienlinhuang1116** [comment]
Thank you, the discussion and answer can be found at #34
